[project]
name = "openmdao-pymoo-driver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.6.0",
    "matplotlib>=3.10.3",
    "networkx>=3.4.2",
    "numpy>=2.2.5",
    "openmdao>=3.38.0",
    "pydoe3>=1.0.4",
    "pymoo>=0.6.1.3",
    "scipy>=1.15.3",
]
